export const INCREMENTING_COUNT = 'INCREMENTING_COUNT';
export const INCREMENTING_COUNT_DONE = 'INCREMENTING_COUNT_DONE';

export const DECREMENTING_COUNT = 'DECREMENTING_COUNT';
export const DECREMENTING_COUNT_DONE = 'DECREMENTING_COUNT_DONE';

export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';
